--DB: ammdb; username: amm; password: amm;--

CREATE TABLE utente (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    email VARCHAR(256) UNIQUE,
    urlImmagine VARCHAR(256),
    frase VARCHAR(256),
    data date,
    password VARCHAR(256) NOT NULL
);

CREATE TABLE post (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creatorId INTEGER,
    FOREIGN KEY (creatorId) REFERENCES utente (id) ON DELETE CASCADE,
    destinationId INTEGER,
    FOREIGN KEY (destinationId) REFERENCES utente (id) ON DELETE CASCADE,
    text VARCHAR(1024),
    image VARCHAR(256)
);

CREATE TABLE gruppo (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    urlImmagine VARCHAR(256)
);

CREATE TABLE followutente (
    follower INTEGER,
    FOREIGN KEY (follower) REFERENCES utente (id) ON DELETE CASCADE,
    followed INTEGER,
    FOREIGN KEY (followed) REFERENCES utente (id) ON DELETE CASCADE,
    PRIMARY KEY(follower,followed)
);

CREATE TABLE followgruppo (
    follower INTEGER,
    FOREIGN KEY (follower) REFERENCES utente (id) ON DELETE CASCADE,
    followed INTEGER,
    FOREIGN KEY (followed) REFERENCES gruppo (id) ON DELETE CASCADE,
    PRIMARY KEY (follower, followed)
);

--Inserimento dati--

--Popolamento utente--
INSERT INTO utente (id, nome, cognome, email, urlImmagine, frase, data, password)
VALUES (default,
        'Kermit',
        'The Frog',
        'kermitthefrog@gmail.com',
        'img/propic1.jpg',
        'Just because you havent found your talent yet, doesnt mean you dont have one.',
        '1955-02-21',
        'kermitvomit');

INSERT INTO utente (id, nome, cognome, email, urlImmagine, frase, data, password)
VALUES (default,
        'Will',
        'Smith',
        'willwillsmiff@outlook.com',
        'img/propic2.jpg',
        'The first step is you have to say that you can.',
        '1968-09-25',
        'willyprince');

INSERT INTO utente (id, nome, cognome, email, urlImmagine, frase, data, password)
VALUES (default,
        'Robin',
        'Williams',
        'robingenie@gmail.com',
        'img/propic3.jpg',
        'No matter what people tell you, words and ideas can change the world.',
        '1951-07-21',
        'robingenie');

INSERT INTO utente (id, nome, cognome, email, urlImmagine, frase, data, password)
VALUES (default,
        'Don',
        'Cheadle',
        'donaldcheadle@gmail.com',
        'img/propic4.jpg',
        'I want to be a part of great things.',
        '1964-10-29',
        'creaash');

INSERT INTO utente (id, nome, cognome, email, urlImmagine, frase, data, password)
VALUES (default,
        'Missing',
        'No',
        'missingno@gmail.com',
        'img/propic5.jpg',
        'I bug your Pokèmon ROM.',
        '1900-01-01',
        'missingno');

--Popolamento gruppo--
INSERT INTO gruppo (id, nome, urlImmagine)
VALUES (default,
        'Hollywood',
        'img/grouppic1.jpg');

--Popolamento gruppo--
INSERT INTO gruppo (id, nome, urlImmagine)
VALUES (default,
        'Puppets',
        'img/grouppic2.jpg');

--Popolamento post--
INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        1,
        1,
        'I just got called from Sony to appear in a brand new videogame: Knack 2.',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        1,
        1,
        'Lets goooooooooo',
        'img/post_2.gif');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        1,
        1,
        'Yall know this aint tea been on hennessy for the past week',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        1,
        1,
        '#NONEOFMYBUSINESS',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        2,
        2,
        'I want the world to be better because I was here',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        2,
        2,
        'You can cry, aint no shame in it',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        2,
        2,
        '',
        'img/prince.jpg');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        2,
        2,
        'https://www.youtube.com/watch?v=gZnronVFyDE Not half bad!',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        3,
        3,
        'In the process of looking for comedy, you have to be deeply honest. 
         And in doing that, youll find out heres the other side. Youll be looking under the rock occasionally for the laughter.',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        3,
        3,
        'Never pick a fight with an ugly person, theyve got nothing to lose.',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        3,
        3,
        'Great experience!',
        'img/genie.jpg');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        3,
        3,
        'Thats my daughter',
        'img/zelda.png');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        4,
        4,
        'Whoa',
        'img/warmachine.jpg');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        4,
        4,
        'Im very critical of myself. Ive yet to see a great performance from this kid. No, its not comfortable;
         I hate watching myself. You dont like when you hear your voice on your voicemail; imagine having to see yourself 30 feet wide and 30 feet big.',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        4,
        4,
        '[when asked by someone if they should be an actor], Id say dont do it if you could anything
            else do that and if you can be dissuaded by me saying that you shouldnt be doing this anyway, if you
            want to really go after it your chances of making it are very very poor if youre a white male between
            the ages of twenty to forty you got the best shot and after that it falls off the shelf that being
            said obviously it can be done and many people have done it and you dont have to be good unfortunately
            and we see that too but you have to be tenacious and have a never say die attitude and with all the
            technology thats out now you can make a movie for two grand you can put yourself out there and package
            yourself in the best light you see',
        '');

INSERT INTO post (id, creatorId, destinationId, text, image)
VALUES (default,
        4,
        4,
        'Ive been doing this since I was 10 years old, inhabiting different people
         and playing different roles. Thirty years later, theres still the same sort of
         excitement I get from it. Its still fun to inhabit different characters and play
         different things, so its all in that panoply of acting.',
        '');

--Popolamento followutente--
INSERT INTO followutente (follower, followed)
VALUES (1,2),
       (1,3),
       (2,1),
       (2,3),
       (2,4),
       (3,1),
       (3,2),
       (3,4),
       (4,2),
       (4,3),
       (5,1),
       (5,3);

INSERT INTO followgruppo (follower, followed)
VALUES (1,2),
       (2,1),
       (3,1),
       (4,1),
       (5,1),
       (5,2);
